package main

import (
	"bytes"
	"encoding/json"
	"net/http"
	"os"
	"time"
)

func addExpense(amount int) {
	payload, _ := json.Marshal(getPayload(amount))
	http.Post("https://spliit.app/api/trpc/groups.expenses.create?batch=1", "application/json", bytes.NewReader(payload))
}

var groupId = os.Getenv("SPLITIT_GROUP_ID")
var paidById = os.Getenv("SPLITIT_PAID_BY_ID")
var paidForId = os.Getenv("SPLITIT_PAID_FOR_ID")

func getPayload(amount int) map[string]any {
	return map[string]any{
		"0": map[string]any{
			"json": map[string]any{
				"groupId": groupId,
				"expenseFormValues": map[string]any{
					"expenseDate": time.Now().Format(time.RFC3339),
					"title":       "Carpool",
					"category":    27,
					"amount":      amount,
					"paidBy":      paidById,
					"paidFor": []any{
						map[string]any{
							"participant": paidForId,
							"shares":      100,
						},
					},
					"splitMode":                   "EVENLY",
					"saveDefaultSplittingOptions": false,
					"isReimbursement":             false,
					"documents":                   []any{},
					"notes":                       "Automatically generated by the Carpool tool",
					"recurrenceRule":              "NONE",
				},
				"participantId": paidById,
			},
			"meta": map[string]any{
				"values": map[string]any{
					"expenseFormValues.expenseDate": []any{"Date"},
				},
			},
		},
	}
}
