package main

import (
	"bytes"
	"encoding/json"
	"net/http"
	"time"
)

func addExpense(amount int) {
	payload, _ := json.Marshal(getPayload(amount))
	http.Post("https://spliit.app/api/trpc/groups.expenses.create?batch=1", "application/json", bytes.NewReader(payload))
}

func getPayload(amount int) map[string]any {
	return map[string]any{
		"0": map[string]any{
			"json": map[string]any{
				"groupId": "042f2ssmbNK_8-TqwxB5E",
				"expenseFormValues": map[string]any{
					"expenseDate": time.Now().AddDate(0, 0, 1).Format(time.RFC3339),
					"title":       "Carpool",
					"category":    27,
					"amount":      amount,
					"paidBy":      "y9MErUKH5I0YXGKbUP2fb",
					"paidFor": []any{
						map[string]any{
							"participant": "aSy9iBBRSSL2WAcr7iWXf",
							"shares":      100,
						},
					},
					"splitMode":                   "EVENLY",
					"saveDefaultSplittingOptions": false,
					"isReimbursement":             false,
					"documents":                   []any{},
					"notes":                       "Automatically generated by Asil's Carpool tool",
					"recurrenceRule":              "NONE",
				},
				"participantId": "y9MErUKH5I0YXGKbUP2fb",
			},
			"meta": map[string]any{
				"values": map[string]any{
					"expenseFormValues.expenseDate": []any{"Date"},
				},
			},
		},
	}
}
